export const FETCH_PAYMENT_DETAILS = "FETCH_PAYMENT_DETAILS";
export const FETCH_PAYMENT_SUCCESS = "FETCH_PAYMENT_SUCCESS";
export const FETCH_PAYMENT_FAILURE = "FETCH_PAYMENT_FAILURE";
export const ADD_PAYMENT_DETAILS = "ADD_PAYMENT_DETAILS";
export const DELETE_PAYMENT_DETAILS = "DELETE_PAYMENT_DETAILS";
export const SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE";
